'use strict';

let PX_DEFAULT = {};
/* internal configurations */
PX_DEFAULT.SERVER_HOST = 'http://localhost:9090';
PX_DEFAULT.SERVER_TO_SERVER_API_URI = '/api/v1/risk';

// Cookie encryption configurations
PX_DEFAULT.CE_KEYLEN = 32;
PX_DEFAULT.CE_IVLEN = 16;
PX_DEFAULT.CE_ITERATIONS = 1000;
PX_DEFAULT.CE_DIGEST = 'sha256';
PX_DEFAULT.CE_ALGO = 'aes-256-cbc';

/* const */
PX_DEFAULT.COOKIE_EVAL = {
    NO_COOKIE: -1,
    COOKIE_INVALID: -2,
    COOKIE_EXPIRED: -3,
    UNEXPECTED_RESULT: -4,
    COOKIE_BAD_SCORE: 0,
    COOKIE_GOOD_SCORE: 1
};

/* actions */
PX_DEFAULT.API_EVAL = {
    S2S_BAD_SCORE: -1,
    UNEXPECTED_RESULT: 0,
    S2S_GOOD_SCORE: 1
};

PX_DEFAULT.BLOCK_TRAFFIC = 0;
PX_DEFAULT.PASS_TRAFFIC = 1;

/* to be defined by the initiating user */
PX_DEFAULT.API_TIMEOUT_MS = 1000;
PX_DEFAULT.COOKIE_ENCRYPTION = true;
PX_DEFAULT.BLOCKING_SCORE = 70;
PX_DEFAULT.COOKIE_SECRET_KEY = 'VYMugZj32NYG5jtpC+Nd39o4SuVCjm5y3QWH7+4xtY6Zc7uvG3/kk9TvbGuyKBTj';
PX_DEFAULT.AUTH_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZXMiOlsicmlza19zY29yZSIsInJlc3RfYXBpIl0sImlhdCI6MTQ2MTU2NjkxOCwic3ViIjoiUFg2MDAyIiwianRpIjoiMjg3YjZiMDktNDBiNC00OTZjLWI2ZjItMGJmMGNiM2E0MTE4In0.PvbQgtjP8wTgjJASBNZxPo_DAxviEhSkr1FVac8JgNQ';
PX_DEFAULT.IP_HEADER = 'px-user-ip';
PX_DEFAULT.DEBUG_MODE = true;
PX_DEFAULT.BLOCKING_HTTP_CODE = 503;
module.exports = PX_DEFAULT;
