'use strict';

let PX_DEFAULT = {};
/* internal configurations */
PX_DEFAULT.SERVER_HOST = 'http://localhost:8080';
PX_DEFAULT.SERVER_TO_SERVER_API_URI = '/api/v1/risk';
PX_DEFAULT.CE_KEYLEN = 32;
PX_DEFAULT.CE_IVLEN = 16;
PX_DEFAULT.CE_DIGEST = 'sha256';
PX_DEFAULT.CE_ALGO = 'aes-256-cbc';

PX_DEFAULT.PASS_TRAFFIC = 1;
PX_DEFAULT.BLOCK_TRAFFIC = 0;

/* to be defined by the initiating user */
PX_DEFAULT.API_TIMEOUT_MS = 1000;
PX_DEFAULT.COOKIE_ENCRYPTION = true;
PX_DEFAULT.BLOCKING_SCORE = 70;
PX_DEFAULT.COOKIE_SECRET_KEY = 'password';
PX_DEFAULT.AUTH_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZXMiOlsicmlza19zY29yZSIsInJlc3RfYXBpIl0sImlhdCI6MTQ2MDY5ODQyNiwic3ViIjoiUFg2MDAyIiwianRpIjoiZTJhMWQzNjctNDFmYS00NDJmLWJmMjktZjI4ZjgxYzdmYjlhIn0.eSy6p6Xv-3JIn-dPRnpmlD99kUWy9KNmAYV2xo7_pdk';

module.exports = PX_DEFAULT;
