'use strict';

let PX_DEFAULT = {};
/* internal configurations */
PX_DEFAULT.SERVER_HOST = 'http://localhost:8080';
PX_DEFAULT.SERVER_TO_SERVER_API_URI = '/api/v1/risk';

// Cookie encryption configurations
PX_DEFAULT.CE_KEYLEN = 32;
PX_DEFAULT.CE_IVLEN = 16;
PX_DEFAULT.CE_ITERATIONS = 1000;
PX_DEFAULT.CE_DIGEST = 'sha256';
PX_DEFAULT.CE_ALGO = 'aes-256-cbc';

PX_DEFAULT.BLOCK_HTML = 'BLOCK';
/* actions */
PX_DEFAULT.SCORE_EVALUATE_ACTION = {
    UNEXPECTED_RESULT: -4,
    NO_COOKIE: -3,
    COOKIE_INVALID: -2,
    COOKIE_EXPIRED: -1,

    PASS_TRAFFIC: 10,
    COOKIE_BLOCK_TRAFFIC: -10,
    S2S_BLOCK_TRAFFIC: -11,

    GOOD_SCORE: 1,
    BAD_SCORE: 0
};


/* to be defined by the initiating user */
PX_DEFAULT.API_TIMEOUT_MS = 1000;
PX_DEFAULT.COOKIE_ENCRYPTION = true;
PX_DEFAULT.BLOCKING_SCORE = 70;
PX_DEFAULT.COOKIE_SECRET_KEY = 'VYMugZj32NYG5jtpC+Nd39o4SuVCjm5y3QWH7+4xtY6Zc7uvG3/kk9TvbGuyKBTj';
PX_DEFAULT.AUTH_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZXMiOlsicmlza19zY29yZSIsInJlc3RfYXBpIl0sImlhdCI6MTQ2MTU2NjkxOCwic3ViIjoiUFg2MDAyIiwianRpIjoiMjg3YjZiMDktNDBiNC00OTZjLWI2ZjItMGJmMGNiM2E0MTE4In0.PvbQgtjP8wTgjJASBNZxPo_DAxviEhSkr1FVac8JgNQ';
PX_DEFAULT.IP_HEADER = 'px-user-ip';
PX_DEFAULT.DEBUG_MODE = false;
PX_DEFAULT.BLOCKING_HTTP_CODE = 503;

module.exports = PX_DEFAULT;
