name: Publish Package to npmjs.org
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup npmrc
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Build library
        run: npm run build
      - name: Publish package
        run: npm publish --access public
        env:
          # TODO: make sure the token is configured
          # https://github.com/PerimeterX/<YOUR-REPO>/settings/secrets/actions
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}