name: Unit Tests
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 10, 12, 14, 16, lts/* ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test